# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /d/Emu/PSVITA/ZeldaROTH-vita

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /d/Emu/PSVITA/ZeldaROTH-vita

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake.exe -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /d/Emu/PSVITA/ZeldaROTH-vita/CMakeFiles /d/Emu/PSVITA/ZeldaROTH-vita/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /d/Emu/PSVITA/ZeldaROTH-vita/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ZeldaROTH

# Build rule for target.
ZeldaROTH: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ZeldaROTH
.PHONY : ZeldaROTH

# fast build rule for target.
ZeldaROTH/fast:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/build
.PHONY : ZeldaROTH/fast

#=============================================================================
# Target rules for targets named ZeldaROTH.self

# Build rule for target.
ZeldaROTH.self: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ZeldaROTH.self
.PHONY : ZeldaROTH.self

# fast build rule for target.
ZeldaROTH.self/fast:
	$(MAKE) -f CMakeFiles/ZeldaROTH.self.dir/build.make CMakeFiles/ZeldaROTH.self.dir/build
.PHONY : ZeldaROTH.self/fast

#=============================================================================
# Target rules for targets named ZeldaROTH_fr.vpk

# Build rule for target.
ZeldaROTH_fr.vpk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ZeldaROTH_fr.vpk
.PHONY : ZeldaROTH_fr.vpk

# fast build rule for target.
ZeldaROTH_fr.vpk/fast:
	$(MAKE) -f CMakeFiles/ZeldaROTH_fr.vpk.dir/build.make CMakeFiles/ZeldaROTH_fr.vpk.dir/build
.PHONY : ZeldaROTH_fr.vpk/fast

Audio.obj: Audio.cpp.obj

.PHONY : Audio.obj

# target to build an object file
Audio.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Audio.cpp.obj
.PHONY : Audio.cpp.obj

Audio.i: Audio.cpp.i

.PHONY : Audio.i

# target to preprocess a source file
Audio.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Audio.cpp.i
.PHONY : Audio.cpp.i

Audio.s: Audio.cpp.s

.PHONY : Audio.s

# target to generate assembly for a file
Audio.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Audio.cpp.s
.PHONY : Audio.cpp.s

Bouclier.obj: Bouclier.cpp.obj

.PHONY : Bouclier.obj

# target to build an object file
Bouclier.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Bouclier.cpp.obj
.PHONY : Bouclier.cpp.obj

Bouclier.i: Bouclier.cpp.i

.PHONY : Bouclier.i

# target to preprocess a source file
Bouclier.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Bouclier.cpp.i
.PHONY : Bouclier.cpp.i

Bouclier.s: Bouclier.cpp.s

.PHONY : Bouclier.s

# target to generate assembly for a file
Bouclier.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Bouclier.cpp.s
.PHONY : Bouclier.cpp.s

Caisse.obj: Caisse.cpp.obj

.PHONY : Caisse.obj

# target to build an object file
Caisse.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Caisse.cpp.obj
.PHONY : Caisse.cpp.obj

Caisse.i: Caisse.cpp.i

.PHONY : Caisse.i

# target to preprocess a source file
Caisse.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Caisse.cpp.i
.PHONY : Caisse.cpp.i

Caisse.s: Caisse.cpp.s

.PHONY : Caisse.s

# target to generate assembly for a file
Caisse.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Caisse.cpp.s
.PHONY : Caisse.cpp.s

Carte.obj: Carte.cpp.obj

.PHONY : Carte.obj

# target to build an object file
Carte.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Carte.cpp.obj
.PHONY : Carte.cpp.obj

Carte.i: Carte.cpp.i

.PHONY : Carte.i

# target to preprocess a source file
Carte.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Carte.cpp.i
.PHONY : Carte.cpp.i

Carte.s: Carte.cpp.s

.PHONY : Carte.s

# target to generate assembly for a file
Carte.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Carte.cpp.s
.PHONY : Carte.cpp.s

Encyclopedie.obj: Encyclopedie.cpp.obj

.PHONY : Encyclopedie.obj

# target to build an object file
Encyclopedie.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Encyclopedie.cpp.obj
.PHONY : Encyclopedie.cpp.obj

Encyclopedie.i: Encyclopedie.cpp.i

.PHONY : Encyclopedie.i

# target to preprocess a source file
Encyclopedie.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Encyclopedie.cpp.i
.PHONY : Encyclopedie.cpp.i

Encyclopedie.s: Encyclopedie.cpp.s

.PHONY : Encyclopedie.s

# target to generate assembly for a file
Encyclopedie.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Encyclopedie.cpp.s
.PHONY : Encyclopedie.cpp.s

Ennemi.obj: Ennemi.cpp.obj

.PHONY : Ennemi.obj

# target to build an object file
Ennemi.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Ennemi.cpp.obj
.PHONY : Ennemi.cpp.obj

Ennemi.i: Ennemi.cpp.i

.PHONY : Ennemi.i

# target to preprocess a source file
Ennemi.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Ennemi.cpp.i
.PHONY : Ennemi.cpp.i

Ennemi.s: Ennemi.cpp.s

.PHONY : Ennemi.s

# target to generate assembly for a file
Ennemi.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Ennemi.cpp.s
.PHONY : Ennemi.cpp.s

Generique.obj: Generique.cpp.obj

.PHONY : Generique.obj

# target to build an object file
Generique.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Generique.cpp.obj
.PHONY : Generique.cpp.obj

Generique.i: Generique.cpp.i

.PHONY : Generique.i

# target to preprocess a source file
Generique.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Generique.cpp.i
.PHONY : Generique.cpp.i

Generique.s: Generique.cpp.s

.PHONY : Generique.s

# target to generate assembly for a file
Generique.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Generique.cpp.s
.PHONY : Generique.cpp.s

Jeu.obj: Jeu.cpp.obj

.PHONY : Jeu.obj

# target to build an object file
Jeu.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Jeu.cpp.obj
.PHONY : Jeu.cpp.obj

Jeu.i: Jeu.cpp.i

.PHONY : Jeu.i

# target to preprocess a source file
Jeu.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Jeu.cpp.i
.PHONY : Jeu.cpp.i

Jeu.s: Jeu.cpp.s

.PHONY : Jeu.s

# target to generate assembly for a file
Jeu.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Jeu.cpp.s
.PHONY : Jeu.cpp.s

Joueur.obj: Joueur.cpp.obj

.PHONY : Joueur.obj

# target to build an object file
Joueur.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Joueur.cpp.obj
.PHONY : Joueur.cpp.obj

Joueur.i: Joueur.cpp.i

.PHONY : Joueur.i

# target to preprocess a source file
Joueur.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Joueur.cpp.i
.PHONY : Joueur.cpp.i

Joueur.s: Joueur.cpp.s

.PHONY : Joueur.s

# target to generate assembly for a file
Joueur.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Joueur.cpp.s
.PHONY : Joueur.cpp.s

Keyboard.obj: Keyboard.cpp.obj

.PHONY : Keyboard.obj

# target to build an object file
Keyboard.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Keyboard.cpp.obj
.PHONY : Keyboard.cpp.obj

Keyboard.i: Keyboard.cpp.i

.PHONY : Keyboard.i

# target to preprocess a source file
Keyboard.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Keyboard.cpp.i
.PHONY : Keyboard.cpp.i

Keyboard.s: Keyboard.cpp.s

.PHONY : Keyboard.s

# target to generate assembly for a file
Keyboard.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Keyboard.cpp.s
.PHONY : Keyboard.cpp.s

Listable.obj: Listable.cpp.obj

.PHONY : Listable.obj

# target to build an object file
Listable.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Listable.cpp.obj
.PHONY : Listable.cpp.obj

Listable.i: Listable.cpp.i

.PHONY : Listable.i

# target to preprocess a source file
Listable.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Listable.cpp.i
.PHONY : Listable.cpp.i

Listable.s: Listable.cpp.s

.PHONY : Listable.s

# target to generate assembly for a file
Listable.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Listable.cpp.s
.PHONY : Listable.cpp.s

Menu.obj: Menu.cpp.obj

.PHONY : Menu.obj

# target to build an object file
Menu.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Menu.cpp.obj
.PHONY : Menu.cpp.obj

Menu.i: Menu.cpp.i

.PHONY : Menu.i

# target to preprocess a source file
Menu.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Menu.cpp.i
.PHONY : Menu.cpp.i

Menu.s: Menu.cpp.s

.PHONY : Menu.s

# target to generate assembly for a file
Menu.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Menu.cpp.s
.PHONY : Menu.cpp.s

Monde.obj: Monde.cpp.obj

.PHONY : Monde.obj

# target to build an object file
Monde.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Monde.cpp.obj
.PHONY : Monde.cpp.obj

Monde.i: Monde.cpp.i

.PHONY : Monde.i

# target to preprocess a source file
Monde.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Monde.cpp.i
.PHONY : Monde.cpp.i

Monde.s: Monde.cpp.s

.PHONY : Monde.s

# target to generate assembly for a file
Monde.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Monde.cpp.s
.PHONY : Monde.cpp.s

Objet.obj: Objet.cpp.obj

.PHONY : Objet.obj

# target to build an object file
Objet.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Objet.cpp.obj
.PHONY : Objet.cpp.obj

Objet.i: Objet.cpp.i

.PHONY : Objet.i

# target to preprocess a source file
Objet.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Objet.cpp.i
.PHONY : Objet.cpp.i

Objet.s: Objet.cpp.s

.PHONY : Objet.s

# target to generate assembly for a file
Objet.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Objet.cpp.s
.PHONY : Objet.cpp.s

Personnage.obj: Personnage.cpp.obj

.PHONY : Personnage.obj

# target to build an object file
Personnage.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Personnage.cpp.obj
.PHONY : Personnage.cpp.obj

Personnage.i: Personnage.cpp.i

.PHONY : Personnage.i

# target to preprocess a source file
Personnage.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Personnage.cpp.i
.PHONY : Personnage.cpp.i

Personnage.s: Personnage.cpp.s

.PHONY : Personnage.s

# target to generate assembly for a file
Personnage.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Personnage.cpp.s
.PHONY : Personnage.cpp.s

Pnj.obj: Pnj.cpp.obj

.PHONY : Pnj.obj

# target to build an object file
Pnj.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Pnj.cpp.obj
.PHONY : Pnj.cpp.obj

Pnj.i: Pnj.cpp.i

.PHONY : Pnj.i

# target to preprocess a source file
Pnj.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Pnj.cpp.i
.PHONY : Pnj.cpp.i

Pnj.s: Pnj.cpp.s

.PHONY : Pnj.s

# target to generate assembly for a file
Pnj.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Pnj.cpp.s
.PHONY : Pnj.cpp.s

Projectile.obj: Projectile.cpp.obj

.PHONY : Projectile.obj

# target to build an object file
Projectile.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Projectile.cpp.obj
.PHONY : Projectile.cpp.obj

Projectile.i: Projectile.cpp.i

.PHONY : Projectile.i

# target to preprocess a source file
Projectile.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Projectile.cpp.i
.PHONY : Projectile.cpp.i

Projectile.s: Projectile.cpp.s

.PHONY : Projectile.s

# target to generate assembly for a file
Projectile.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Projectile.cpp.s
.PHONY : Projectile.cpp.s

Snipe.obj: Snipe.cpp.obj

.PHONY : Snipe.obj

# target to build an object file
Snipe.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Snipe.cpp.obj
.PHONY : Snipe.cpp.obj

Snipe.i: Snipe.cpp.i

.PHONY : Snipe.i

# target to preprocess a source file
Snipe.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Snipe.cpp.i
.PHONY : Snipe.cpp.i

Snipe.s: Snipe.cpp.s

.PHONY : Snipe.s

# target to generate assembly for a file
Snipe.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Snipe.cpp.s
.PHONY : Snipe.cpp.s

Statut.obj: Statut.cpp.obj

.PHONY : Statut.obj

# target to build an object file
Statut.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Statut.cpp.obj
.PHONY : Statut.cpp.obj

Statut.i: Statut.cpp.i

.PHONY : Statut.i

# target to preprocess a source file
Statut.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Statut.cpp.i
.PHONY : Statut.cpp.i

Statut.s: Statut.cpp.s

.PHONY : Statut.s

# target to generate assembly for a file
Statut.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Statut.cpp.s
.PHONY : Statut.cpp.s

Texte.obj: Texte.cpp.obj

.PHONY : Texte.obj

# target to build an object file
Texte.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Texte.cpp.obj
.PHONY : Texte.cpp.obj

Texte.i: Texte.cpp.i

.PHONY : Texte.i

# target to preprocess a source file
Texte.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Texte.cpp.i
.PHONY : Texte.cpp.i

Texte.s: Texte.cpp.s

.PHONY : Texte.s

# target to generate assembly for a file
Texte.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/Texte.cpp.s
.PHONY : Texte.cpp.s

ZoneRect.obj: ZoneRect.cpp.obj

.PHONY : ZoneRect.obj

# target to build an object file
ZoneRect.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/ZoneRect.cpp.obj
.PHONY : ZoneRect.cpp.obj

ZoneRect.i: ZoneRect.cpp.i

.PHONY : ZoneRect.i

# target to preprocess a source file
ZoneRect.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/ZoneRect.cpp.i
.PHONY : ZoneRect.cpp.i

ZoneRect.s: ZoneRect.cpp.s

.PHONY : ZoneRect.s

# target to generate assembly for a file
ZoneRect.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/ZoneRect.cpp.s
.PHONY : ZoneRect.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ZeldaROTH.dir/build.make CMakeFiles/ZeldaROTH.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ZeldaROTH"
	@echo "... edit_cache"
	@echo "... ZeldaROTH.self"
	@echo "... rebuild_cache"
	@echo "... ZeldaROTH_fr.vpk"
	@echo "... Audio.obj"
	@echo "... Audio.i"
	@echo "... Audio.s"
	@echo "... Bouclier.obj"
	@echo "... Bouclier.i"
	@echo "... Bouclier.s"
	@echo "... Caisse.obj"
	@echo "... Caisse.i"
	@echo "... Caisse.s"
	@echo "... Carte.obj"
	@echo "... Carte.i"
	@echo "... Carte.s"
	@echo "... Encyclopedie.obj"
	@echo "... Encyclopedie.i"
	@echo "... Encyclopedie.s"
	@echo "... Ennemi.obj"
	@echo "... Ennemi.i"
	@echo "... Ennemi.s"
	@echo "... Generique.obj"
	@echo "... Generique.i"
	@echo "... Generique.s"
	@echo "... Jeu.obj"
	@echo "... Jeu.i"
	@echo "... Jeu.s"
	@echo "... Joueur.obj"
	@echo "... Joueur.i"
	@echo "... Joueur.s"
	@echo "... Keyboard.obj"
	@echo "... Keyboard.i"
	@echo "... Keyboard.s"
	@echo "... Listable.obj"
	@echo "... Listable.i"
	@echo "... Listable.s"
	@echo "... Menu.obj"
	@echo "... Menu.i"
	@echo "... Menu.s"
	@echo "... Monde.obj"
	@echo "... Monde.i"
	@echo "... Monde.s"
	@echo "... Objet.obj"
	@echo "... Objet.i"
	@echo "... Objet.s"
	@echo "... Personnage.obj"
	@echo "... Personnage.i"
	@echo "... Personnage.s"
	@echo "... Pnj.obj"
	@echo "... Pnj.i"
	@echo "... Pnj.s"
	@echo "... Projectile.obj"
	@echo "... Projectile.i"
	@echo "... Projectile.s"
	@echo "... Snipe.obj"
	@echo "... Snipe.i"
	@echo "... Snipe.s"
	@echo "... Statut.obj"
	@echo "... Statut.i"
	@echo "... Statut.s"
	@echo "... Texte.obj"
	@echo "... Texte.i"
	@echo "... Texte.s"
	@echo "... ZoneRect.obj"
	@echo "... ZoneRect.i"
	@echo "... ZoneRect.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

